// Auto-generated by deploy script - DO NOT EDIT MANUALLY
const CONFIG = {
    // Hardhat Local Network
    NETWORK: {
        chainId: '0x7a69',              // 31337 in decimal (Hardhat)
        chainName: 'Hardhat Local',
        rpcUrl: 'http://127.0.0.1:8545',
        blockExplorer: '',
        currency: {
            name: 'CLD',
            symbol: 'CLD',
            decimals: 18
        }
    },

    // Server Configuration
    SERVER: {
        url: 'http://localhost:3000'
    },

    // Smart Contract
    CONTRACT: {
        address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
        abi: [
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileId",
                                "type": "string"
                        }
                ],
                "name": "FileDeleted",
                "type": "event"
        },
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileId",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "oldFolder",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "newFolder",
                                "type": "string"
                        }
                ],
                "name": "FileMoved",
                "type": "event"
        },
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileId",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "oldName",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "newName",
                                "type": "string"
                        }
                ],
                "name": "FileRenamed",
                "type": "event"
        },
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "recipient",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileId",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileName",
                                "type": "string"
                        }
                ],
                "name": "FileShared",
                "type": "event"
        },
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileId",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "ipfsHash",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "fileName",
                                "type": "string"
                        },
                        {
                                "indexed": false,
                                "internalType": "uint256",
                                "name": "fileSize",
                                "type": "uint256"
                        },
                        {
                                "indexed": false,
                                "internalType": "uint256",
                                "name": "uploadTime",
                                "type": "uint256"
                        },
                        {
                                "indexed": false,
                                "internalType": "bool",
                                "name": "isEncrypted",
                                "type": "bool"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "folderName",
                                "type": "string"
                        }
                ],
                "name": "FileUploaded",
                "type": "event"
        },
        {
                "anonymous": false,
                "inputs": [
                        {
                                "indexed": true,
                                "internalType": "address",
                                "name": "owner",
                                "type": "address"
                        },
                        {
                                "indexed": false,
                                "internalType": "string",
                                "name": "folderName",
                                "type": "string"
                        }
                ],
                "name": "FolderCreated",
                "type": "event"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_folderName",
                                "type": "string"
                        }
                ],
                "name": "createFolder",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_fileId",
                                "type": "string"
                        }
                ],
                "name": "deleteFile",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "uint256",
                                "name": "_index",
                                "type": "uint256"
                        }
                ],
                "name": "getFile",
                "outputs": [
                        {
                                "components": [
                                        {
                                                "internalType": "string",
                                                "name": "fileId",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "ipfsHash",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "fileName",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "fileSize",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "uploadTime",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "address",
                                                "name": "owner",
                                                "type": "address"
                                        },
                                        {
                                                "internalType": "bool",
                                                "name": "isEncrypted",
                                                "type": "bool"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "folderName",
                                                "type": "string"
                                        }
                                ],
                                "internalType": "struct CloudStorage.File",
                                "name": "",
                                "type": "tuple"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "getFileCount",
                "outputs": [
                        {
                                "internalType": "uint256",
                                "name": "",
                                "type": "uint256"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "getFilesSharedWithMe",
                "outputs": [
                        {
                                "components": [
                                        {
                                                "internalType": "string",
                                                "name": "fileId",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "ipfsHash",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "fileName",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "fileSize",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "uploadTime",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "address",
                                                "name": "owner",
                                                "type": "address"
                                        },
                                        {
                                                "internalType": "bool",
                                                "name": "isEncrypted",
                                                "type": "bool"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "folderName",
                                                "type": "string"
                                        }
                                ],
                                "internalType": "struct CloudStorage.File[]",
                                "name": "",
                                "type": "tuple[]"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "getMyFiles",
                "outputs": [
                        {
                                "components": [
                                        {
                                                "internalType": "string",
                                                "name": "fileId",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "ipfsHash",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "fileName",
                                                "type": "string"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "fileSize",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "uint256",
                                                "name": "uploadTime",
                                                "type": "uint256"
                                        },
                                        {
                                                "internalType": "address",
                                                "name": "owner",
                                                "type": "address"
                                        },
                                        {
                                                "internalType": "bool",
                                                "name": "isEncrypted",
                                                "type": "bool"
                                        },
                                        {
                                                "internalType": "string",
                                                "name": "folderName",
                                                "type": "string"
                                        }
                                ],
                                "internalType": "struct CloudStorage.File[]",
                                "name": "",
                                "type": "tuple[]"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [],
                "name": "getMyFolders",
                "outputs": [
                        {
                                "internalType": "string[]",
                                "name": "",
                                "type": "string[]"
                        }
                ],
                "stateMutability": "view",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_fileId",
                                "type": "string"
                        },
                        {
                                "internalType": "string",
                                "name": "_folderName",
                                "type": "string"
                        }
                ],
                "name": "moveFileToFolder",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_fileId",
                                "type": "string"
                        },
                        {
                                "internalType": "string",
                                "name": "_newName",
                                "type": "string"
                        }
                ],
                "name": "renameFile",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_fileId",
                                "type": "string"
                        },
                        {
                                "internalType": "address",
                                "name": "_recipient",
                                "type": "address"
                        }
                ],
                "name": "shareFile",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        },
        {
                "inputs": [
                        {
                                "internalType": "string",
                                "name": "_fileId",
                                "type": "string"
                        },
                        {
                                "internalType": "string",
                                "name": "_ipfsHash",
                                "type": "string"
                        },
                        {
                                "internalType": "string",
                                "name": "_fileName",
                                "type": "string"
                        },
                        {
                                "internalType": "uint256",
                                "name": "_fileSize",
                                "type": "uint256"
                        },
                        {
                                "internalType": "bool",
                                "name": "_isEncrypted",
                                "type": "bool"
                        },
                        {
                                "internalType": "string",
                                "name": "_folderName",
                                "type": "string"
                        }
                ],
                "name": "uploadFile",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function"
        }
]
    }
};
